#!/bin/bash

cd /tmp/ || return 1

REPO_URL=$1
REPO_NAME=$(basename "$REPO_URL" | cut -d'.' -f0)

# Clone given repository
if [ ! -d "$REPO_NAME" ]; then
	log "Cloning $REPO_NAME repository"
	git clone --depth=1 "$REPO_URL" 1>/dev/null 2>&1
	cd "$REPO_NAME" || return 1
else
	cd "$REPO_NAME" || return 1
	git pull 1>/dev/null 2>&1
fi
echo "  [OK]..."
