#!/bin/bash

BINARIES=()
CHECK_PATH="$(pwd)"

verify_binaries() {
	for item in "${BINARIES[@]}"; do
		# Get just the binary name without the path
		local binary_name
		binary_name=$(basename "$item")

		# Construct the full path to check
		local full_path="${CHECK_PATH:+$CHECK_PATH/}${item}"

		if [ -f "$full_path" ]; then
			echo "  [OK] Building ${item}"

			# Compress & copy the binary to `BINARIES_DIR`, flattening the structure
			if file "$full_path" | grep -q "ELF"; then

				if ! file "$full_path" | grep -q "64-bit"; then
					echo "  [FAIL] ${item} is not 64-bit"
					return 1
				fi

				if ! file "$full_path" | grep -q "ARM aarch64"; then
					echo "[FAIL] ${item} is not ARM aarch64"
					return 1
				fi

				if ! file "$full_path" | grep -q "statically linked"; then
					echo "  [FAIL] ${item} is not statically linked"
					return 1
				fi

				if ! file "$full_path" | grep -q "stripped"; then
					echo "  [FAIL] ${item} is not stripped"
					return 1
				fi

				# NOTE: Sometimes production binaries are not writable, which is required by UPX
				chmod +w "$full_path"
				upx_output=$(upx --best --lzma --quiet "$full_path" 2>&1)
				upx_exit_code=$?
				if [ $upx_exit_code -eq 0 ]; then
					echo "  [OK] Packing with UPX"
				elif echo "$upx_output" | grep -q "AlreadyPackedException"; then
					echo "  [WARN] UPX detected, skipping UPX for $item"
				else
					printf "  [FAIL] UPX failed for %s $item:\n\n%s", "$item", "$upx_output"
					return 1
				fi
			fi
			cp "$full_path" "${BINARIES_DIR}/${binary_name}"
			echo "  [OK] Copying ${binary_name}"
		else
			echo "  [FAIL] ${item} not found in ${CHECK_PATH}"
			return 1
		fi
	done

	log "All binaries verified successfully"
	return 0
}

# Parse arguments
while (("$#")); do
	case "$1" in
	-p | --path)
		CHECK_PATH=$2
		shift 2
		;;
	-b | --binaries)
		IFS=' ' read -ra BINARIES <<<"$2"
		shift 2
		;;
	-h | --help)
		log "Usage: $0 [-p|--path <path>] [-b|--binaries <space-separated binaries>]"
		exit 0
		;;
	-*)
		log "Error: Unknown option: $1" >&2
		exit 1
		;;
	*)
		BINARIES+=("$1")
		shift
		;;
	esac
done

if [ ${#BINARIES[@]} -eq 0 ]; then
	log "Error: No binaries specified. Use -b|--binaries option or provide them as arguments."
	exit 1
fi

log "Verifying build for: $(printf '%s ' "${BINARIES[@]}")"
verify_binaries
exit $?
